const teams = {
  "Sub-11A": [
    { number: 48, name: "Heitor Kiuti",       photo: "assets/sub11a/heitor-kiuti.jpg" },
    { number: 55, name: "Alexandre Lopes",    photo: "assets/sub11a/alexandre-lopes.jpg" },
    { number: 90, name: "Afonso Almeida",     photo: "assets/sub11a/afonso-almeida.jpg" },
    { number: 13, name: "Benjamin Bahia",     photo: "assets/sub11a/benjamin-bahia.jpg" },
    { number: 15, name: "Davi Silva",         photo: "assets/sub11a/default.png" },
    { number: 18, name: "Rodrigo José",       photo: "assets/sub11a/rodrigo-jose.jpg" },
    { number: 97, name: "Duarte Santos",      photo: "assets/sub11a/duarte-santos.jpg" },
    { number: 99, name: "Manuel Brito",       photo: "assets/sub11a/manuel-brito.jpg" },
    { number: 17, name: "Miguel Bessa",       photo: "assets/sub11a/miguel-bessa.jpg" },
    { number: 30, name: "João Sousa",         photo: "assets/sub11a/joao-sousa.jpg" },
    { number: 32, name: "Santiago Correia",   photo: "assets/sub11a/santiago-correia.jpg" },
    { number:  7, name: "Rodrigo Marques",    photo: "assets/sub11a/rodrigo-marques.jpg" },
    { number: 22, name: "Gabriel Mercedes",   photo: "assets/sub11a/gabriel-mercedes.jpg" },
    { number: 35, name: "Rodrigo Rebelo",     photo: "assets/sub11a/rodrigo-rebelo.jpg" },
    { number:  5, name: "Henrique Ferreira",  photo: "assets/sub11a/henrique-ferreira.jpg" },
    { number: 80, name: "Vicente Rodrigues",  photo: "assets/sub11a/vicente-rodrigues.jpg" }
  ],
  "Sub-11B": [
    { number: 10, name: "Martim Soares",      photo: "assets/sub11b/martim-soares.jpg" },
    { number: 19, name: "Duarte Lopes",       photo: "assets/sub11b/duarte-lopes.jpg" },
    { number: 20, name: "Vicente Nascimento", photo: "assets/sub11b/vicente-nascimento.jpg" },
    { number: 21, name: "Mateus Vaz",         photo: "assets/sub11b/mateus-vaz.jpg" },
    { number: 23, name: "Duarte Pereira",     photo: "assets/sub11b/duarte-pereira.jpg" },
    { number: 25, name: "Duarte Correia",     photo: "assets/sub11b/duarte-correia.jpg" },
    { number: 27, name: "Gonçalo Silva",      photo: "assets/sub11b/goncalo-silva.jpg" },
    { number: 28, name: "Carlos Pinto",       photo: "assets/sub11b/rafael-pinto.jpg" },
    { number:  3, name: "Daniel Silva",       photo: "assets/sub11b/daniel-silva.jpg" },
    { number: 33, name: "Rodrigo Gonçalves",  photo: "assets/sub11b/rodrigo-brilhante.jpg" },
    { number:  4, name: "Francisco Barros",   photo: "assets/sub11b/francisco-barros.jpg" },
    { number: 41, name: "Martim Cardoso",     photo: "assets/sub11b/martim-cardoso.jpg" },
    { number:  6, name: "Lourenço Jesus",     photo: "assets/sub11b/lourenco-rebelo-de-jesus.jpg" },
    { number:  8, name: "João Ferreira",      photo: "assets/sub11b/joao-ferreira.jpg" },
    { number: 84, name: "Daniel Monteiro",    photo: "assets/sub11b/daniel-monteiro.jpg" },
    { number:  9, name: "José Pereira",       photo: "assets/sub11b/jose-miguel-pereira.jpg" }
  ],
  "Sub-13": [
    { number:  1, name: "Tiago Ribeiro",      photo: "assets/sub13/tiago-ribeiro.jpg" },
    { number: 10, name: "Lucca Quintal",      photo: "assets/sub13/lucca-quintal.jpg" },
    { number: 16, name: "Leonardo Miranda",   photo: "assets/sub13/leonardo-miranda.jpg" },
    { number: 20, name: "D. Rebordão",        photo: "assets/sub13/dinis-rebordao.jpg" },
    { number: 33, name: "Kiko",               photo: "assets/sub13/francisco-salgueiro.jpg" },
    { number: 40, name: "Rodri C.",           photo: "assets/sub13/rodrigo-cardoso.jpg" },
    { number:  8, name: "Zi",                 photo: "assets/sub13/guilherme-amaro.jpg" },
    { number: 11, name: "Rodrigo F.",         photo: "assets/sub13/rodrigo-fernandes.jpg" },
    { number: 13, name: "Paulo M.",           photo: "assets/sub13/paulo-figueiredo.jpg" },
    { number: 14, name: "Jota",               photo: "assets/sub13/joao-amaro.jpg" },
    { number: 21, name: "Salva",              photo: "assets/sub13/salvador-oliveira.jpg" },
    { number: 28, name: "Pedro C.",           photo: "assets/sub13/pedro-costa.jpg" },
    { number: 30, name: "Sara",               photo: "assets/sub13/sara-pires.jpg" },
    { number:  4, name: "Lorenzo",            photo: "assets/sub13/lorenzo_dce.jpg" }
  ],
  "Sub-15": [
    { number:  1, name: "Pedro Cardoso",          photo: "assets/sub15/pedro-cardoso.jpg" },
    { number: 99, name: "Gabriel Assunção",       photo: "assets/sub15/gabriel-assuncao.jpg" },
    { number: 46, name: "Carlos Gabriel Pinto",   photo: "assets/sub15/gabriel-pinto.jpg" },
    { number:  6, name: "João Bernardo Mangana",  photo: "assets/sub15/bernardo-mangana.jpg" },
    { number: 12, name: "Santiago Oliveira",      photo: "assets/sub15/santi-oliveira.jpg" },
    { number: 14, name: "José Patricio",          photo: "assets/sub15/jose-patricio.jpg" },
    { number: 22, name: "Daniel Rodrigues",       photo: "assets/sub15/daniel-rodrigues.jpg" },
    { number: 29, name: "Afonso Cabral",          photo: "assets/sub15/afonso-cabral.jpg" },
    { number: 79, name: "Diogo Lopes",            photo: "assets/sub15/diogo-lopes.jpg" },
    { number:  8, name: "Simão Henriques",        photo: "assets/sub15/simao-henriques.jpg" },
    { number: 87, name: "Francisco Borralho",     photo: "assets/sub15/francisco-borralho.jpg" },
    { number: 17, name: "Gabriel Baptista",       photo: "assets/sub15/gabriel-baptista.jpg" },
    { number: 28, name: "Rodrigo Lourenço",       photo: "assets/sub15/rodrigo-lourenco.jpg" },
    { number:  4, name: "António Figueiredo",     photo: "assets/sub15/antonio-figueiredo.jpg" },
    { number:  7, name: "Leonardo Machado",       photo: "assets/sub15/leo-machado.jpg" },
    { number:  9, name: "Henrique Vieira",        photo: "assets/sub15/henrique.jpg" },
    { number: 10, name: "Maria Gouveia",          photo: "assets/sub15/maria.jpg" }
  ],
  "Sub-19": [
    { number:  1, name: "Diogo Henrique",     photo: "assets/sub19/diogo-h.jpg" },
    { number: 12, name: "Felipe Silva",       photo: "assets/sub19/felipe.jpg" },
    { number: 21, name: "Alexandre Borralho", photo: "assets/sub19/alex-borralho.jpg" },
    { number: 10, name: "Tomás Gomes",        photo: "assets/sub19/tomas-gomes.png" },
    { number: 11, name: "Martim Carvalho",    photo: "assets/sub19/marim-carvalho.jpg" },
    { number: 17, name: "José Santos",        photo: "assets/sub19/jose-santos.jpg" },
    { number: 20, name: "Salvador Lourenço",  photo: "assets/sub19/salvador-lourenco.jpg" },
    { number:  7, name: "Tomás Marques",      photo: "assets/sub19/tomas-marques.jpg" },
    { number:  8, name: "Francisco Oliveira", photo: "assets/sub19/francisco-oliveira.jpg" },
    { number: 15, name: "Gabriel Duarte",     photo: "assets/sub19/gabriel-duarte.jpg" },
    { number: 79, name: "Diego Chaves",       photo: "assets/sub19/diego-chaves.jpg" },
    { number: 14, name: "Kiko",               photo: "assets/sub19/kiko.jpg" },
    { number:  4, name: "Simão Rocha",        photo: "assets/sub19/simao.PNG.0x600_q85_crop_scale.png" }
  ]
};
